# Generated by Django 3.2.7 on 2021-10-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalawarenessApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userfeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=25)),
                ('phno', models.IntegerField()),
                ('subject', models.CharField(max_length=25)),
                ('msg', models.CharField(max_length=300)),
            ],
        ),
    ]
