# Generated by Django 3.2.7 on 2021-10-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalawarenessApp', '0002_userfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('paymode', models.CharField(max_length=25)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
